/**
 * Canon protestante (66 libros) con nombres en español como en el lector.
 * Sirve para mostrar todos los capítulos aunque la base local esté incompleta.
 */

export const SPANISH_BOOKS: readonly string[] = [
  "Génesis",
  "Éxodo",
  "Levítico",
  "Números",
  "Deuteronomio",
  "Josué",
  "Jueces",
  "Rut",
  "1 Samuel",
  "2 Samuel",
  "1 Reyes",
  "2 Reyes",
  "1 Crónicas",
  "2 Crónicas",
  "Esdras",
  "Nehemías",
  "Ester",
  "Job",
  "Salmos",
  "Proverbios",
  "Eclesiastés",
  "Cantares",
  "Isaías",
  "Jeremías",
  "Lamentaciones",
  "Ezequiel",
  "Daniel",
  "Oseas",
  "Joel",
  "Amós",
  "Abdías",
  "Jonás",
  "Miqueas",
  "Nahúm",
  "Habacuc",
  "Sofonías",
  "Hageo",
  "Zacarías",
  "Malaquías",
  "Mateo",
  "Marcos",
  "Lucas",
  "Juan",
  "Hechos",
  "Romanos",
  "1 Corintios",
  "2 Corintios",
  "Gálatas",
  "Efesios",
  "Filipenses",
  "Colosenses",
  "1 Tesalonicenses",
  "2 Tesalonicenses",
  "1 Timoteo",
  "2 Timoteo",
  "Tito",
  "Filemón",
  "Hebreos",
  "Santiago",
  "1 Pedro",
  "2 Pedro",
  "1 Juan",
  "2 Juan",
  "3 Juan",
  "Judas",
  "Apocalipsis",
] as const;

/** Número de capítulos por libro (mismo orden que SPANISH_BOOKS). */
export const CHAPTERS_PER_BOOK: readonly number[] = [
  50, 40, 27, 36, 34, 24, 21, 4, 31, 24, 22, 25, 29, 36, 10, 13, 10, 42, 150, 31, 12, 8, 66, 52, 5, 48, 12, 14, 3,
  9, 1, 4, 7, 3, 3, 3, 2, 14, 4, 28, 16, 24, 21, 28, 16, 16, 13, 6, 6, 4, 4, 5, 3, 6, 4, 3, 1, 13, 5, 5, 3, 5, 1,
  1, 1, 22,
];

const BOOK_TO_CHAPTERS = new Map<string, number>(
  SPANISH_BOOKS.map((name, i) => [name, CHAPTERS_PER_BOOK[i] ?? 1]),
);

/** Nombre en inglés para labs.bible.org (NET). */
const SPANISH_TO_LABS_ENGLISH: Record<string, string> = {
  Génesis: "Genesis",
  Éxodo: "Exodus",
  Levítico: "Leviticus",
  Números: "Numbers",
  Deuteronomio: "Deuteronomy",
  Josué: "Joshua",
  Jueces: "Judges",
  Rut: "Ruth",
  "1 Samuel": "1 Samuel",
  "2 Samuel": "2 Samuel",
  "1 Reyes": "1 Kings",
  "2 Reyes": "2 Kings",
  "1 Crónicas": "1 Chronicles",
  "2 Crónicas": "2 Chronicles",
  Esdras: "Ezra",
  Nehemías: "Nehemiah",
  Ester: "Esther",
  Job: "Job",
  Salmos: "Psalms",
  Proverbios: "Proverbs",
  Eclesiastés: "Ecclesiastes",
  Cantares: "Song of Songs",
  Isaías: "Isaiah",
  Jeremías: "Jeremiah",
  Lamentaciones: "Lamentations",
  Ezequiel: "Ezekiel",
  Daniel: "Daniel",
  Oseas: "Hosea",
  Joel: "Joel",
  Amós: "Amos",
  Abdías: "Obadiah",
  Jonás: "Jonah",
  Miqueas: "Micah",
  Nahúm: "Nahum",
  Habacuc: "Habakkuk",
  Sofonías: "Zephaniah",
  Hageo: "Haggai",
  Zacarías: "Zechariah",
  Malaquías: "Malachi",
  Mateo: "Matthew",
  Marcos: "Mark",
  Lucas: "Luke",
  Juan: "John",
  Hechos: "Acts",
  Romanos: "Romans",
  "1 Corintios": "1 Corinthians",
  "2 Corintios": "2 Corinthians",
  Gálatas: "Galatians",
  Efesios: "Ephesians",
  Filipenses: "Philippians",
  Colosenses: "Colossians",
  "1 Tesalonicenses": "1 Thessalonians",
  "2 Tesalonicenses": "2 Thessalonians",
  "1 Timoteo": "1 Timothy",
  "2 Timoteo": "2 Timothy",
  Tito: "Titus",
  Filemón: "Philemon",
  Hebreos: "Hebrews",
  Santiago: "James",
  "1 Pedro": "1 Peter",
  "2 Pedro": "2 Peter",
  "1 Juan": "1 John",
  "2 Juan": "2 John",
  "3 Juan": "3 John",
  Judas: "Jude",
  Apocalipsis: "Revelation",
};

export function getChapterCountForBook(book: string): number {
  return BOOK_TO_CHAPTERS.get(book) ?? 150;
}

export function bookSpanishToLabsEnglish(book: string): string | null {
  return SPANISH_TO_LABS_ENGLISH[book] ?? null;
}

export function chapterNumbersForBook(book: string): number[] {
  const n = getChapterCountForBook(book);
  return Array.from({ length: n }, (_, i) => i + 1);
}
